In [1]:
 
import numpy as np

In [2]:
x1 = [2.5, 0.5, 2.2, 1.9, 3.1, 2.3, 2, 1, 1.5, 1.1]
 
 

In [3]:
mean = np.mean(x1)
std_dev = np.std(x1)
 
standardized_data_x1 = (mean - x1)
standardized_data_x1 = standardized_data_x1
 
print("Standardized data x1:")
print(standardized_data_x1)

Standardized data x1:
[-0.69  1.31 -0.39 -0.09 -1.29 -0.49 -0.19  0.81  0.31  0.71]


In [4]:
x2 = [2.4, 0.7, 2.9, 2.2, 3.0, 2.7, 1.6, 1.1, 1.6, 0.9]
 
mean = np.mean(x2)
std_dev = np.std(x2)
 
standardized_data_x2 = (x2 - mean)
standardized_data_x2 = standardized_data_x2
 
print("\nStandardized data x2:")
print(standardized_data_x2)


Standardized data x2:
[ 0.49 -1.21  0.99  0.29  1.09  0.79 -0.31 -0.81 -0.31 -1.01]


In [5]:
data = np.array([standardized_data_x1, standardized_data_x2])
 
cov_matrix = np.cov(data)
 
print("\nCovariance matrix:")
print(cov_matrix)


Covariance matrix:
[[ 0.61655556 -0.61544444]
 [-0.61544444  0.71655556]]


In [6]:
from numpy.linalg import eig
 
w, v = eig(cov_matrix)
 
print("\nEigenvalues (w):")
print(w)
 
print("\nEigenvectors (v):")
print(v)
 
print("\nnp.transpose(v):")
print(np.transpose(v))


Eigenvalues (w):
[0.0490834  1.28402771]

Eigenvectors (v):
[[-0.73517866  0.6778734 ]
 [-0.6778734  -0.73517866]]

np.transpose(v):
[[-0.73517866 -0.6778734 ]
 [ 0.6778734  -0.73517866]]


In [7]:

a = np.transpose(standardized_data_x1)
b = np.transpose(standardized_data_x2)
 
data_t = np.array([a, b])
 
print("\ndata_t:")
print(data_t)


data_t:
[[-0.69  1.31 -0.39 -0.09 -1.29 -0.49 -0.19  0.81  0.31  0.71]
 [ 0.49 -1.21  0.99  0.29  1.09  0.79 -0.31 -0.81 -0.31 -1.01]]


In [8]:
 
final = np.transpose(v) @ data_t
print("\nfinal:")
print(final)


final:
[[ 0.17511531 -0.14285723 -0.38437499 -0.13041721  0.20949846 -0.17528244
   0.3498247  -0.04641726 -0.01776463  0.16267529]
 [-0.82797019  1.77758033 -0.99219749 -0.27421042 -1.67580142 -0.9129491
   0.09910944  1.14457216  0.43804614  1.22382056]]


In [9]:
print("\nnp.transpose(final):")
print(np.transpose(final))
 


np.transpose(final):
[[ 0.17511531 -0.82797019]
 [-0.14285723  1.77758033]
 [-0.38437499 -0.99219749]
 [-0.13041721 -0.27421042]
 [ 0.20949846 -1.67580142]
 [-0.17528244 -0.9129491 ]
 [ 0.3498247   0.09910944]
 [-0.04641726  1.14457216]
 [-0.01776463  0.43804614]
 [ 0.16267529  1.22382056]]
